config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new]

  get '/register', to: 'chefs#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many :recipes
  has_many :likes
  validates :chefname, presence: true, length: {minimum: 3, maximum: 40}
  validates :email, presence: true, length: {maximum: 100},
             uniqueness: {case_sensitive: false}

  has_secure_password
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :chef
  belongs_to :recipe

  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  has_many :likes
  validates :chef_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 100}
  validates :summary, presence: true, length: {minimum: 10, maximum: 150}
  validates :describtion, presence: true, length: {minimum: 20, maximum: 200}
  mount_uploader :picture, PictureUploader

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  def index
    @chefs = Chef.all
  end

  def show
    @chef = Chef.find(params[:id])
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Account has been created successfully"
      session[:chef_id] = @chef.id
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def edit
    @chef = Chef.find(params[:id])
  end

  def update
    @chef = Chef.find(params[:id])
    if @chef.update(chef_params)
      flash[:success] = "Account updates successfully"
      redirect_to recipes_path
    else
      render 'edit'
    end
  end

  private
    def chef_params
      params.require(:chef).permit(:chefname, :email, :password)
    end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new
  end

  def create
    chef = Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      redirect_to recipes_path
    else
      flash.now[:danger] = "email or password are not correct"
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.find(1)
    if @recipe.save
      flash[:success] = "Successfully created..."
      redirect_to recipes_path
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = "Successfully updates..."
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    #code
  end

  def like
    @recipe = Recipe.find(params[:id])
    like = Like.create(like: params[:like], chef: Chef.first, recipe: @recipe)
    if like.valid?
      flash[:success] = "done"
      redirect_back fallback_location: like_recipe_path(@recipe)
    else
      flash[:danger] = "like/dislike once"
      redirect_back fallback_location: like_recipe_path(@recipe)
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :describtion)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef, options = { size: 80})
    #<% gravatar_for recipe.chef, size: 100 %>
    gravatar_id = Digest::MDS::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/views/chefs/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @chef do |f| %>
      <%= f.label :chefname %>
      <%= f.text_field :chefname %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit(@chef.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>
<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
  </div>
</div>

<% @chefs.each do |chef| %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <p>
        <h5>Chef name: <%= chef.chefname %></h5>
      </p>
    </div>
  </div>
<% end %>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Register your account" %>
<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title:  "Chef: " + @chef.chefname %>
<% @chef.recipes.each do |recipe| %>
  <div class="row">
    <div class="col-lg-6 well col-lg-offset-3">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class="quiet"><small> <%= time_ago_in_words(recipe.created_at) %> ago </small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; MyRecipes 2018</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-mid-10">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert"> &#215; </a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navegation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "myRecipes", root_path, class: "btn btn-lg btn-success", id: "logo" %>
    <div class="nav_item">
      <%= link_to "login", login_path, class: "btn btn-default btn-warning" %>
    </div>
    <div class="nav_item">
      <%= link_to "link1", "", class: "btn btn-default btn-warning" %>
    </div>
    <% if logged_in? %>
    <div class="nav_item">
      <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
    </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navegation' %>
    <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Log in' %>
<div class="row">
  <div class="well col-md-6 col-md-offset-3">
    <%= form_tag 'login' do %>
      <%= label_tag :email %>
      <%= text_field_tag :email %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= submit_tag 'Login', class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotran">
  <h1>welcome to RecipesApp</h1>
  <h2>this is alot of talk </h2>
  <%= link_to "Sign up now", register_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      view recipes as guest user
    </h3>
    <h2 class="left">
      browse and view recipes as guest and sign up later
    </h2>
    <p>
      <%= link_to "browse recipes listings", recipes_path, class: "btn btn-warning btn-small" %>
    </p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      view recipes as guest user
    </h3>
    <h2 class="left">
      browse and view recipes as guest and sign up later
    </h2>
    <p>
      <%= link_to "browse recipes listings", "", class: "btn btn-warning btn-small" %>
    </p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      view recipes as guest user
    </h3>
    <h2 class="left">
      browse and view recipes as guest and sign up later
    </h2>
    <p>
      <%= link_to "browse recipes listings", "", class: "btn btn-warning btn-small" %>
    </p>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @recipe do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :summary %>
      <%= f.text_field :summary %>

      <%= f.label :describtion %>
      <%= f.text_area :describtion, rows: 10 %>

      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>
<hr/>

<% @recipes.each do |recipe| %>
  <div class="row">

    <div class="col-md-2">
      <section class="chef-info center">

        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>

    <div class="col-lg-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class="quiet"><small> <%= time_ago_in_words(recipe.created_at) %> ago </small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>

  </div>
  <hr/>
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new Recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title:  @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <p>
      <h5>Brought to u by: <%= @recipe.chef.chefname %></h5>
    </p>
  </div>
  <div class="col-md-8">
    <%= link_to "Edit Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <h3><%= @recipe.summary %></h3>
    <div class="well">
      <p>
        <strong>steps: </strong>
      </p>
      <%= simple_format(@recipe.describtion) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to "Back to all recipes", recipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>